### ISSUE TITLE
多重ベクタを扱えるようにする

### ISSUE THREAD

**Issue by s-yata** [groonga/grngo#18]
#### 概要

テーブル参照のベクタ型について，参照先がベクタであれば，多重のベクタになります．
現在は多重のベクタを扱うことができません．
`GetValue()` で多重のベクタを扱えるようにすることが目標です．

**Comment by kou** [comment]
（Goの話ではなく、Groongaの話として、）前、森さんと話した時にイテレーターのようなものを導入して、すべての値を一気にロードするのではなく、個別の値を順に取得できるようにしたい、と言っていました。（Groongaではaccessorというのを`grn_obj_get_value()`したときに同じ状況になります。）

森さんにはまだ話していないアイディアですが、`grn_accessor`を`grn_path`と`grn_traverser`に分けて、`grn_path`には`grn_accessor`が持っているパス情報（`column1.column2.coumn3`みたいなやつ）だけを持たせて、そいつから値を取得するのは`grn_traverser`が頑張る、`grn_traverser`はカーソルみたいなインターフェイスかコールバックを渡すインターフェイスを提供する、というのを考えています。

**Comment by s-yata** [comment]
`grn_obj_get_value()` でひとつずつ参照を辿るような実装にしました．

Go 側の実装には `reflect` を使っています．
現状の実装では効率が悪いのですが，ひとまずは動く状態を目指しました．

この機能に関しては，性能より使えるかどうかが重要だと思うので，テストを増やして問題が見つからなければ OK とします．

**Comment by s-yata** [comment]
#### SetValue()

すべての組み合わせを調べたわけではありませんが，指定された値が参照先テーブルのキーとして有効であれば使えるようです．
ここから先は，また別のマイルストーンとチケットでやることにします．

#### GetValue()

大丈夫なようです．
